name: Gradle Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [ '16.0.2' ]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Echo JAVA_HOME
      run: echo $JAVA_HOME
    - name: Verify Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Execute build
      run: ./gradlew --info --stacktrace build
    - name: Execute runtime
      run: ./gradlew --info --stacktrace runtime
    - name: Execute jpackage
      run: ./gradlew --info --stacktrace jpackage
    - name: Show build/jpackage content
      if: runner.os != 'Windows'
      run: ls -al build/jpackage
    - name: Show logback files in DMG package
      if: runner.os == 'macOS'
      run: hdiutil attach build/jpackage/*.dmg && find /Volumes/non-modular-hello/non-modular-hello.app/Contents -name "logback*"
    - name: Upload DMG as an artifact
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v2
      with:
        name: non-modular-hello-jdk${{ matrix.java }}-${{ matrix.os }}-dmg
        path: build/jpackage/*.dmg
    - name: Upload EXE as an artifact
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v2
      with:
        name: non-modular-hello-jdk${{ matrix.java }}-${{ matrix.os }}-exe
        path: build/jpackage/*.exe
    - name: Upload MSI as an artifact
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v2
      with:
        name: non-modular-hello-jdk${{ matrix.java }}-${{ matrix.os }}-msi
        path: build/jpackage/*.msi
    - name: Show logback files in DEB package
      if: runner.os == 'Linux'
      run: dpkg -c build/jpackage/*.deb | grep logback
    - name: Upload DEB as an artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v2
      with:
        name: non-modular-hello-jdk${{ matrix.java }}-${{ matrix.os }}-deb
        path: build/jpackage/*.deb
    - name: Show logback files in RPM package
      if: runner.os == 'Linux'
      run: rpm -qlp build/jpackage/*.rpm | grep logback
    - name: Upload RPM as an artifact
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v2
      with:
        name: non-modular-hello-jdk${{ matrix.java }}-${{ matrix.os }}-rpm
        path: build/jpackage/*.rpm
